@startuml

participant "MyTelProviderSimulator(8080)\nScenario 'ReceivingCarrier" as ReceivingCarrier
participant "CoolTelProviderSimulator(9090)\nScenario 'DonatingCarrier'" as DonatingCarrier


ReceivingCarrier -> DonatingCarrier : PortingNegotiationRequest
activate DonatingCarrier
DonatingCarrier -->> ReceivingCarrier : Acknowledgment
deactivate DonatingCarrier

...

DonatingCarrier -> ReceivingCarrier : PortingNegotiationResponse
activate ReceivingCarrier
ReceivingCarrier -->> DonatingCarrier : Acknowledgment
deactivate ReceivingCarrier

@enduml
