@startuml

participant "Receiving Carrier" as ReceivingCarrier
participant "Donating Carrier" as DonatingCarrier


ReceivingCarrier -> DonatingCarrier : PortingNegotiationRequest
activate DonatingCarrier
DonatingCarrier -->> ReceivingCarrier : Acknowledgment
deactivate DonatingCarrier

...

DonatingCarrier -> ReceivingCarrier : PortingNegotiationResponse
note right: porting negotiation request\napproved / rejected
activate ReceivingCarrier
ReceivingCarrier -->> DonatingCarrier : Acknowledgment
deactivate ReceivingCarrier

@enduml
