@startuml

participant "CoolTelProviderSimulator(8080)\nas ReceivingCarrier" as ReceivingCarrier
participant "MyTelProviderSimulator(9090)\nas DonatingCarrier" as DonatingCarrier


ReceivingCarrier -> DonatingCarrier : PortingNegotiationRequest
activate DonatingCarrier
DonatingCarrier -->> ReceivingCarrier : Acknowledgment
deactivate DonatingCarrier

...

DonatingCarrier -> ReceivingCarrier : PortingNegotiationResponse
activate ReceivingCarrier
ReceivingCarrier -->> DonatingCarrier : Acknowledgment
deactivate ReceivingCarrier

@enduml
